### ISSUE TITLE
新的2个bug: 1、前2页是白板，第三页开始正常显示，2、刷新数据时，底部圆点指示器不会更新，会无限增加新的

### ISSUE THREAD

**Issue by mingdong88** [raotongGitup/BannerViewpage#2]
很高兴看到0.02修复版，谢谢！
新的2个bug: 1、前2页是白板，第三页开始正常显示，2、刷新数据时，底部圆点指示器不会更新，会无限增加新的
希望能修复。

**Comment by raotongGitup** [comment]
我这边测试没有发现您说的这个白屏问题，圆点重复代码已经上传，预计下一个版本提交

**Comment by mingdong88** [comment]
> 我这边测试没有发现您说的这个白屏问题，圆点重复代码已经上传，预计下一个版本提交

新旧版本都是复现前两张白屏，红米7pro和小米5都是真机。无论是本地图片还是网络图片都是前两张白屏，第三张开始可以了，循环到第一张又正常显示了。（本地的图片时白屏，这个不知什么原因了，如果是网络图也可能是因为网络问题）

**Comment by mingdong88** [comment]
当前是可以正常显示了，没有白板，（我删除了先前的apk，可能有缓存？）。
刷新数据后，第一个圆点一直是暗色（选中状态）

**Comment by mingdong88** [comment]
多次刷新数据后，会跳出当前页面
报错：

`D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxx, PID: 15303
    java.lang.NullPointerException: Attempt to invoke virtual method 'void xxx.banner.DotIndicatorView.setDrawable(android.graphics.drawable.Drawable)' on a null object reference
        at xxx.banner.BannerView.pageSelect(BannerView.java:215)
        at xxx.banner.BannerView.access$100(BannerView.java:29)
        at xxx.banner.BannerView$3.onPageSelected(BannerView.java:192)
        at androidx.viewpager.widget.ViewPager.dispatchOnPageSelected(ViewPager.java:1947)
        at androidx.viewpager.widget.ViewPager.scrollToItem(ViewPager.java:686)
        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:670)
        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
        at androidx.viewpager.widget.ViewPager.setCurrentItem(ViewPager.java:612)
        at xxx.banner.BannerViewPage$1.handleMessage(BannerViewPage.java:35)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)`

**Comment by raotongGitup** [comment]
这个已经修改了，这个在v0.0.3中已经更新，谢谢发现的问题

**Comment by mingdong88** [comment]
自动滑动颜色正确显示，手触摸滑动还是没修正。也没有绝对居中，一起改下吧，辛苦

**Comment by mingdong88** [comment]
已star，用在项目中，感谢修复！

**Comment by raotongGitup** [comment]
这个代码已经修改，暂时还没有生成库，欢迎再次发现问题

**Comment by raotongGitup** [comment]
https://github.com/raotongGitup/Banner 这个是用viewpage2实现的banner
